### ISSUE TITLE
Karma Tests: Difficult to break out of watch mode

### ISSUE THREAD

**Issue by samwhale** [swissspidy/web-stories-wp#10876]
## Bug Description

After #6304, breaking out of `watch` mode in the karma tests is difficult.

## Expected Behaviour

Should be easy to break out of karma tests when in `watch` mode.

## Steps to Reproduce

1. Focus a test using `fit`
2. Run `npm run test:karma:story-editor:watch`
3. After the test is complete, try to break out with `ctrl+c`. Takes a long time, and then should see an error when it finally breaks:

```js
Webpack stopped watching.
10 03 2022 11:20:02.205:ERROR [karma-server]: UncaughtException: Error: Puppeteer was unable to kill the process which ran the browser binary.
This means that, on future Puppeteer launches, Puppeteer might not be able to launch the browser.
Please check your open processes and ensure that the browser processes that Puppeteer launched have been killed.
If you think this is a bug, please report it on the Puppeteer issue tracker.
Error cause: Error: kill EPERM
    at process.kill (node:internal/process/per_thread:220:13)
    at BrowserRunner.kill (/web-stories-wp/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:185:29)
    at process.<anonymous> (/web-stories-wp/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:146:22)
    at process.emit (node:events:532:35)
    at BrowserRunner.kill (/web-stories-wp/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:189:23)
    at process.<anonymous> (/web-stories-wp/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:146:22)
    at process.emit (node:events:532:35)
10 03 2022 11:20:02.205:ERROR [karma-server]: Error: Puppeteer was unable to kill the process which ran the browser binary.
This means that, on future Puppeteer launches, Puppeteer might not be able to launch the browser.
Please check your open processes and ensure that the browser processes that Puppeteer launched have been killed.
If you think this is a bug, please report it on the Puppeteer issue tracker.
Error cause: Error: kill EPERM
    at process.kill (node:internal/process/per_thread:220:13)
    at BrowserRunner.kill (/web-stories-wp/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:185:29)
    at process.<anonymous> (/web-stories-wp/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:146:22)
    at process.emit (node:events:532:35)
    at BrowserRunner.kill (/web-stories-wp/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:189:23)
    at process.<anonymous> (/web-stories-wp/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:146:22)
    at process.emit (node:events:532:35)
10 03 2022 11:20:02.213:WARN [Chrome 100.0.4889.0 (Mac OS 10.15.7)]: Disconnected (0 times) Client disconnected from CONNECTED state (server shutting down)
Chrome 100.0.4889.0 (Mac OS 10.15.7) ERROR
  Disconnected Client disconnected from CONNECTED state (server shutting down)
Chrome 100.0.4889.0 (Mac OS 10.15.7) ERROR
  Disconnected Client disconnected from CONNECTED state (server shutting down)
(node:64274) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [Server]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
^C
```

## Screenshots

![let-me-out](https://user-images.githubusercontent.com/22185279/157707814-15cf1b0d-7315-4a84-8ab0-61786dce19bb.gif)

## Additional Context

- Plugin Version: 1.19.0-alpha
- WordPress Version: 5.9.1
- Operating System: MacOSX BigSur 11.6.2
- Browser: Chrome

**Comment by swissspidy** [comment]
Interesting 🤔 

Any initial ideas on what might be happening?

This is where our puppeteer launcher is supposed to close the browser I think:

https://github.com/GoogleForCreators/web-stories-wp/blob/59978a121b05efac476480bc9398a66191d7c84d/packages/karma-puppeteer-launcher/src/index.cjs#L90-L95
