### ISSUE TITLE
Insert by link media not working

### ISSUE THREAD

**Issue by santoshgistto** [swissspidy/web-stories-wp#12849]
## Bug Description
Insert by link in story editor not working 

## Expected Behaviour
 Should be able to insert image or video link in the story page

## Steps to Reproduce
Please see the video below

## Video

https://user-images.githubusercontent.com/12577046/208142876-a4e54bd2-1566-4089-99cf-ae75fe673de4.mp4

## Additional Context
> Look like `getHotlinkInfo` is `undefined`
### Logs
`"TypeError: getHotlinkInfo is not a function
    at http://localhost:60364/main.9cea836e5c8816c3770b.hot-update.js:140:31
    at onClick (http://localhost:60364/main.iframe.bundle.js:160739:70)
    at HTMLUnknownElement.callCallback (http://localhost:60364/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_dist_es-cb6a83.iframe.bundle.js:119620:14)
    at Object.invokeGuardedCallbackDev (http://localhost:60364/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_dist_es-cb6a83.iframe.bundle.js:119669:16)
    at invokeGuardedCallback (http://localhost:60364/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_dist_es-cb6a83.iframe.bundle.js:119731:31)
    at invokeGuardedCallbackAndCatchFirstError (http://localhost:60364/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_dist_es-cb6a83.iframe.bundle.js:119745:25)
    at executeDispatch (http://localhost:60364/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_dist_es-cb6a83.iframe.bundle.js:123918:3)
    at processDispatchQueueItemsInOrder (http://localhost:60364/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_dist_es-cb6a83.iframe.bundle.js:123950:7)
    at processDispatchQueue (http://localhost:60364/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_dist_es-cb6a83.iframe.bundle.js:123963:5)
    at dispatchEventsForPlugins (http://localhost:60364/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_dist_es-cb6a83.iframe.bundle.js:123974:3)"`

> https://github.com/GoogleForCreators/web-stories-wp/blob/main/packages/story-editor/src/components/hotlinkModal/useHotlinkModal.js

- Plugin Version: v1.28.0
- WordPress Version:
- Operating System: MAC
- Browser: Chrome

**Comment by swissspidy** [comment]
Thanks for your report.

We haven't added the hotlink functionality to the storybook playground editor, so this is expected.

If you want to build your own editor, you'd have to implement the `getHotlinkInfo` function yourself.

**Comment by santoshgistto** [comment]
Thanks @swissspidy
