### ISSUE TITLE
🐛 when using the `output` module

### ISSUE THREAD

**Issue by pietrop** [swissspidy/web-stories-wp#12965]
Following up on this comment https://github.com/GoogleForCreators/web-stories-wp/issues/6440#issuecomment-1400754419
I want to use the [output](https://github.com/GoogleForCreators/web-stories-wp/tree/main/packages/output) module to generate AMP HTML Markup as part of another project. 

I created a sample project here  https://github.com/pietrop/vite-gws-editor-test using [vite](https://vitejs.dev) to bootstrap a react app.

But I am running into a few issues importing the module.

I import the version specified in the comment https://github.com/GoogleForCreators/web-stories-wp/issues/6440#issuecomment-1400754419 - [here ](https://github.com/pietrop/vite-gws-editor-test/blob/main/package.json#L12)

```
npm install @googleforcreators/output@0.1.202301231653
```

```
"@googleforcreators/output": "0.1.202301231653",
```

And at a minimum I am trying to
-  import the [`OutputStory` from the module](https://github.com/pietrop/vite-gws-editor-test/blob/main/src/App.jsx#L4)
- I've taken [some story props](https://github.com/pietrop/vite-gws-editor-test/blob/main/src/App.jsx#L7-L104) from [the `output` module story test page](https://github.com/GoogleForCreators/web-stories-wp/blob/main/packages/output/src/test/story.js#L35-L130)
- And was hoping to [display a Google Web Story AMP HTML Markup](https://github.com/pietrop/vite-gws-editor-test/blob/main/src/App.jsx#L136-L144) 🐛 

## Bug Description

After following the steps above, and running `npm run dev` I get the following error in the console 

Also see screenshot below, to see it in context

```sh
getDefinitionForType.ts:23 Uncaught Error: No element definition found for 'text'
    at o19 (getDefinitionForType.ts:23:15)
    at OutputElement (element.js:58:34)
    at renderWithHooks (react-dom.development.js:16305:18)
    at mountIndeterminateComponent (react-dom.development.js:20074:13)
    at beginWork (react-dom.development.js:21587:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27451:7)
    at performUnitOfWork (react-dom.development.js:26557:12)
 ```

## Expected Behaviour

I'd expect to be able to import `OutputStory` from `@googleforcreators/output` without error 

## Steps to Reproduce

See https://github.com/pietrop/vite-gws-editor-test  and steps described above

## Screenshots

<img width="818" alt="Screen Shot 2023-01-23 at 6 38 51 PM" src="https://user-images.githubusercontent.com/4661975/214176647-f8df62d6-9c0e-425d-8260-8a55be6a3245.png">

## Additional Context

- Plugin Version: @googleforcreators/output@0.1.202301231653
- WordPress Version: _NA_
- Operating System: Mac OSX 
- Browser: Chrome 108.0.5359.124 (Official Build) (x86_64)

Code:
- [packages/elements/src/utils/getDefinitionForType.ts#L23](https://github.com/GoogleForCreators/web-stories-wp/blob/2f21b00d44a954a63794988da0740ab33c6d1a7f/packages/elements/src/utils/getDefinitionForType.ts#L23)
- [` getDefinitionForType` invoked inside `packages/output/src/element.js#L58`](https://github.com/GoogleForCreators/web-stories-wp/blob/2f21b00d44a954a63794988da0740ab33c6d1a7f/packages/output/src/element.js#L58)

**Comment by pietrop** [comment]
I got it working in another branch https://github.com/pietrop/vite-gws-editor-test/pull/1 after bringing in 

```
import { registerElementType } from '@googleforcreators/elements';
import { elementTypes } from '@googleforcreators/element-library';
```
and registering the type, same as in the tests  [packages/output/src/test/story.js#L31](https://github.com/GoogleForCreators/web-stories-wp/blob/2f21b00d44a954a63794988da0740ab33c6d1a7f/packages/output/src/test/story.js#L31)

```
elementTypes.forEach(registerElementType);
```

**Comment by pietrop** [comment]
I also had to use `import { renderToStaticMarkup } from 'react-dom/server';` directly because using `@googleforcreators/react` was causing some issues.

the version of react didn't seem to be compatible with react 18

```
npm i @googleforcreators/react
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: vite-gws-editor-test@0.0.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^17.0.2" from @googleforcreators/react@0.1.202301231653
npm ERR! node_modules/@googleforcreators/react
npm ERR!   @googleforcreators/react@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/pietropassarelli/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pietropassarelli/.npm/_logs/2023-01-23T23_55_37_051Z-debug-0.log
```

but even after using the legancy peer dependancy flag, I would still get some erros

<details><summary><code>react-is</code> and <code>immutable</code> seemed to be missing, see here for more details</summary>

```
Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
✘ [ERROR] Could not resolve "react-is"

    node_modules/styled-components/dist/styled-components.browser.esm.js:1:62:
      1 │ ... e,isElement as t,isValidElementType as n}from"react-is";import r,{useState as o,useContext as s,useM...
        ╵                                                  ~~~~~~~~~~

  You can mark the path "react-is" as external to exclude it from the bundle, which will remove this
  error.

✘ [ERROR] Could not resolve "immutable"

    node_modules/draft-js-utils/esm/getEntityRanges.js:1:31:
      1 │ import { OrderedSet, is } from 'immutable';
        ╵                                ~~~~~~~~~~~

  You can mark the path "immutable" as external to exclude it from the bundle, which will remove
  this error.

✘ [ERROR] Could not resolve "immutable"

    node_modules/draft-js-import-element/esm/stateFromElement.js:17:51:
      17 │ import { List, Map, OrderedSet, Repeat, Seq } from 'immutable';
         ╵                                                    ~~~~~~~~~~~

  You can mark the path "immutable" as external to exclude it from the bundle, which will remove
  this error.

/Users/pietropassarelli/CODE/vite-gws-editor-test/node_modules/esbuild/lib/main.js:1604
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 3 errors:
node_modules/draft-js-import-element/esm/stateFromElement.js:17:51: ERROR: Could not resolve "immutable"
node_modules/draft-js-utils/esm/getEntityRanges.js:1:31: ERROR: Could not resolve "immutable"
node_modules/styled-components/dist/styled-components.browser.esm.js:1:62: ERROR: Could not resolve "react-is"
    at failureErrorWithLog (/Users/pietropassarelli/CODE/vite-gws-editor-test/node_modules/esbuild/lib/main.js:1604:15)
    at /Users/pietropassarelli/CODE/vite-gws-editor-test/node_modules/esbuild/lib/main.js:1056:28
    at runOnEndCallbacks (/Users/pietropassarelli/CODE/vite-gws-editor-test/node_modules/esbuild/lib/main.js:1476:61)
    at buildResponseToResult (/Users/pietropassarelli/CODE/vite-gws-editor-test/node_modules/esbuild/lib/main.js:1054:7)
    at /Users/pietropassarelli/CODE/vite-gws-editor-test/node_modules/esbuild/lib/main.js:1166:14
    at responseCallbacks.<computed> (/Users/pietropassarelli/CODE/vite-gws-editor-test/node_modules/esbuild/lib/main.js:701:9)
    at handleIncomingPacket (/Users/pietropassarelli/CODE/vite-gws-editor-test/node_modules/esbuild/lib/main.js:756:9)
    at Socket.readFromStdout (/Users/pietropassarelli/CODE/vite-gws-editor-test/node_modules/esbuild/lib/main.js:677:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: {
        column: 51,
        file: 'node_modules/draft-js-import-element/esm/stateFromElement.js',
        length: 11,
        line: 17,
        lineText: "import { List, Map, OrderedSet, Repeat, Seq } from 'immutable';",
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: null,
          text: 'You can mark the path "immutable" as external to exclude it from the bundle, which will remove this error.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "immutable"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 31,
        file: 'node_modules/draft-js-utils/esm/getEntityRanges.js',
        length: 11,
        line: 1,
        lineText: "import { OrderedSet, is } from 'immutable';",
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: null,
          text: 'You can mark the path "immutable" as external to exclude it from the bundle, which will remove this error.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "immutable"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 62,
        file: 'node_modules/styled-components/dist/styled-components.browser.esm.js',
        length: 10,
        line: 1,
        lineText: 'import{typeOf as e,isElement as t,isValidElementType as n}from"react-is";import r,{useState as o,useContext as s,useMemo as i,useEffect as a,useRef as c,createElement as u,useDebugValue as l,useLayoutEffect as d}from"react";import h from"shallowequal";import p from"@emotion/stylis";import f from"@emotion/unitless";import m from"@emotion/is-prop-valid";import y from"hoist-non-react-statics";function v(){return(v=Object.assign||function(e){for(var t=1;t<arguments.length;t++){var n=arguments[t];for(var r in n)Object.prototype.hasOwnProperty.call(n,r)&&(e[r]=n[r])}return e}).apply(this,arguments)}var g=function(e,t){for(var n=[e[0]],r=0,o=t.length;r<o;r+=1)n.push(t[r],e[r+1]);return n},S=function(t){return null!==t&&"object"==typeof t&&"[object Object]"===(t.toString?t.toString():Object.prototype.toString.call(t))&&!e(t)},w=Object.freeze([]),E=Object.freeze({});function b(e){return"function"==typeof e}function _(e){return"production"!==process.env.NODE_ENV&&"string"==typeof e&&e||e.displayName||e.name||"Component"}function N(e){return e&&"string"==typeof e.styledComponentId}var A="undefined"!=typeof process&&(process.env.REACT_APP_SC_ATTR||process.env.SC_ATTR)||"data-styled",C="5.3.6",I="undefined"!=typeof window&&"HTMLElement"in window,P=Boolean("boolean"==typeof SC_DISABLE_SPEEDY?SC_DISABLE_SPEEDY:"undefined"!=typeof process&&void 0!==process.env.REACT_APP_SC_DISABLE_SPEEDY&&""!==process.env.REACT_APP_SC_DISABLE_SPEEDY?"false"!==process.env.REACT_APP_SC_DISABLE_SPEEDY&&process.env.REACT_APP_SC_DISABLE_SPEEDY:"undefined"!=typeof process&&void 0!==process.env.SC_DISABLE_SPEEDY&&""!==process.env.SC_DISABLE_SPEEDY?"false"!==process.env.SC_DISABLE_SPEEDY&&process.env.SC_DISABLE_SPEEDY:"production"!==process.env.NODE_ENV),O={},R="production"!==process.env.NODE_ENV?{1:"Cannot create styled-component for component: %s.\\n\\n",2:"Can\'t collect styles once you\'ve consumed a `ServerStyleSheet`\'s styles! `ServerStyleSheet` is a one off instance for each server-side render cycle.\\n\\n- Are you trying to reuse it across renders?\\n- Are you accidentally calling collectStyles twice?\\n\\n",3:"Streaming SSR is only supported in a Node.js environment; Please do not try to call this method in the browser.\\n\\n",4:"The `StyleSheetManager` expects a valid target or sheet prop!\\n\\n- Does this error occur on the client and is your target falsy?\\n- Does this error occur on the server and is the sheet falsy?\\n\\n",5:"The clone method cannot be used on the client!\\n\\n- Are you running in a client-like environment on the server?\\n- Are you trying to run SSR on the client?\\n\\n",6:"Trying to insert a new style tag, but the given Node is unmounted!\\n\\n- Are you using a custom target that isn\'t mounted?\\n- Does your document not have a valid head element?\\n- Have you accidentally removed a style tag manually?\\n\\n",7:\'ThemeProvider: Please return an object from your "theme" prop function, e.g.\\n\\n```js\\ntheme={() => ({})}\\n```\\n\\n\',8:\'ThemeProvider: Please make your "theme" prop an object.\\n\\n\',9:"Missing document `<head>`\\n\\n",10:"Cannot find a StyleSheet instance. Usually this happens if there are multiple copies of styled-components loaded at once. Check out this issue for how to troubleshoot and fix the common cases where this situation can happen: https://github.com/styled-components/styled-components/issues/1941#issuecomment-417862021\\n\\n",11:"_This error was replaced with a dev-time warning, it will be deleted for v4 final._ [createGlobalStyle] received children which will not be rendered. Please use the component without passing children elements.\\n\\n",12:"It seems you are interpolating a keyframe declaration (%s) into an untagged string. This was supported in styled-components v3, but is not longer supported in v4 as keyframes are now injected on-demand. Please wrap your string in the css\\\\`\\\\` helper which ensures the styles are injected correctly. See https://www.styled-components.com/docs/api#css\\n\\n",13:"%s is not a styled component and cannot be referred to via component selector. See https://www.styled-components.com/docs/advanced#referring-to-other-components for more details.\\n\\n",14:\'ThemeProvider: "theme" prop is required.\\n\\n\',15:"A stylis plugin has been supplied that is not named. We need a name for each plugin to be able to prevent styling collisions between different stylis configurations within the same app. Before you pass your plugin to `<StyleSheetManager stylisPlugins={[]}>`, please make sure each plugin is uniquely-named, e.g.\\n\\n```js\\nObject.defineProperty(importedPlugin, \'name\', { value: \'some-unique-name\' });\\n```\\n\\n",16:"Reached the limit of how many styled components may be created at group %s.\\nYou may only create up to 1,073,741,824 components. If you\'re creating components dynamically,\\nas for instance in your render method then you may be running into this limitation.\\n\\n",17:"CSSStyleSheet could not be found on HTMLStyleElement.\\nHas styled-components\' style tag been unmounted or altered by another script?\\n"}:{};function D(){for(var e=arguments.length<=0?void 0:arguments[0],t=[],n=1,r=arguments.length;n<r;n+=1)t.push(n<0||arguments.length<=n?void 0:arguments[n]);return t.forEach((function(t){e=e.replace(/%[a-z]/,t)})),e}function j(e){for(var t=arguments.length,n=new Array(t>1?t-1:0),r=1;r<t;r++)n[r-1]=arguments[r];throw"production"===process.env.NODE_ENV?new Error("An error occurred. See https://git.io/JUIaE#"+e+" for more information."+(n.length>0?" Args: "+n.join(", "):"")):new Error(D.apply(void 0,[R[e]].concat(n)).trim())}var T=function(){function e(e){this.groupSizes=new Uint32Array(512),this.length=512,this.tag=e}var t=e.prototype;return t.indexOfGroup=function(e){for(var t=0,n=0;n<e;n++)t+=this.groupSizes[n];return t},t.insertRules=function(e,t){if(e>=this.groupSizes.length){for(var n=this.groupSizes,r=n.length,o=r;e>=o;)(o<<=1)<0&&j(16,""+e);this.groupSizes=new Uint32Array(o),this.groupSizes.set(n),this.length=o;for(var s=r;s<o;s++)this.groupSizes[s]=0}for(var i=this.indexOfGroup(e+1),a=0,c=t.length;a<c;a++)this.tag.insertRule(i,t[a])&&(this.groupSizes[e]++,i++)},t.clearGroup=function(e){if(e<this.length){var t=this.groupSizes[e],n=this.indexOfGroup(e),r=n+t;this.groupSizes[e]=0;for(var o=n;o<r;o++)this.tag.deleteRule(n)}},t.getGroup=function(e){var t="";if(e>=this.length||0===this.groupSizes[e])return t;for(var n=this.groupSizes[e],r=this.indexOfGroup(e),o=r+n,s=r;s<o;s++)t+=this.tag.getRule(s)+"/*!sc*/\\n";return t},e}(),x=new Map,k=new Map,V=1,B=function(e){if(x.has(e))return x.get(e);for(;k.has(V);)V++;var t=V++;return"production"!==process.env.NODE_ENV&&((0|t)<0||t>1<<30)&&j(16,""+t),x.set(e,t),k.set(t,e),t},z=function(e){return k.get(e)},M=function(e,t){t>=V&&(V=t+1),x.set(e,t),k.set(t,e)},G="style["+A+\'][data-styled-version="5.3.6"]\',L=new RegExp("^"+A+\'\\\\.g(\\\\d+)\\\\[id="([\\\\w\\\\d-]+)"\\\\].*?"([^"]*)\'),F=function(e,t,n){for(var r,o=n.split(","),s=0,i=o.length;s<i;s++)(r=o[s])&&e.registerName(t,r)},Y=function(e,t){for(var n=(t.textContent||"").split("/*!sc*/\\n"),r=[],o=0,s=n.length;o<s;o++){var i=n[o].trim();if(i){var a=i.match(L);if(a){var c=0|parseInt(a[1],10),u=a[2];0!==c&&(M(u,c),F(e,u,a[3]),e.getTag().insertRules(c,r)),r.length=0}else r.push(i)}}},q=function(){return"undefined"!=typeof __webpack_nonce__?__webpack_nonce__:null},H=function(e){var t=document.head,n=e||t,r=document.createElement("style"),o=function(e){for(var t=e.childNodes,n=t.length;n>=0;n--){var r=t[n];if(r&&1===r.nodeType&&r.hasAttribute(A))return r}}(n),s=void 0!==o?o.nextSibling:null;r.setAttribute(A,"active"),r.setAttribute("data-styled-version","5.3.6");var i=q();return i&&r.setAttribute("nonce",i),n.insertBefore(r,s),r},$=function(){function e(e){var t=this.element=H(e);t.appendChild(document.createTextNode("")),this.sheet=function(e){if(e.sheet)return e.sheet;for(var t=document.styleSheets,n=0,r=t.length;n<r;n++){var o=t[n];if(o.ownerNode===e)return o}j(17)}(t),this.length=0}var t=e.prototype;return t.insertRule=function(e,t){try{return this.sheet.insertRule(t,e),this.length++,!0}catch(e){return!1}},t.deleteRule=function(e){this.sheet.deleteRule(e),this.length--},t.getRule=function(e){var t=this.sheet.cssRules[e];return void 0!==t&&"string"==typeof t.cssText?t.cssText:""},e}(),W=function(){function e(e){var t=this.element=H(e);this.nodes=t.childNodes,this.length=0}var t=e.prototype;return t.insertRule=function(e,t){if(e<=this.length&&e>=0){var n=document.createTextNode(t),r=this.nodes[e];return this.element.insertBefore(n,r||null),this.length++,!0}return!1},t.deleteRule=function(e){this.element.removeChild(this.nodes[e]),this.length--},t.getRule=function(e){return e<this.length?this.nodes[e].textContent:""},e}(),U=function(){function e(e){this.rules=[],this.length=0}var t=e.prototype;return t.insertRule=function(e,t){return e<=this.length&&(this.rules.splice(e,0,t),this.length++,!0)},t.deleteRule=function(e){this.rules.splice(e,1),this.length--},t.getRule=function(e){return e<this.length?this.rules[e]:""},e}(),J=I,X={isServer:!I,useCSSOMInjection:!P},Z=function(){function e(e,t,n){void 0===e&&(e=E),void 0===t&&(t={}),this.options=v({},X,{},e),this.gs=t,this.names=new Map(n),this.server=!!e.isServer,!this.server&&I&&J&&(J=!1,function(e){for(var t=document.querySelectorAll(G),n=0,r=t.length;n<r;n++){var o=t[n];o&&"active"!==o.getAttribute(A)&&(Y(e,o),o.parentNode&&o.parentNode.removeChild(o))}}(this))}e.registerId=function(e){return B(e)};var t=e.prototype;return t.reconstructWithOptions=function(t,n){return void 0===n&&(n=!0),new e(v({},this.options,{},t),this.gs,n&&this.names||void 0)},t.allocateGSInstance=function(e){return this.gs[e]=(this.gs[e]||0)+1},t.getTag=function(){return this.tag||(this.tag=(n=(t=this.options).isServer,r=t.useCSSOMInjection,o=t.target,e=n?new U(o):r?new $(o):new W(o),new T(e)));var e,t,n,r,o},t.hasNameForId=function(e,t){return this.names.has(e)&&this.names.get(e).has(t)},t.registerName=function(e,t){if(B(e),this.names.has(e))this.names.get(e).add(t);else{var n=new Set;n.add(t),this.names.set('... 16933 more characters,
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: null,
          text: 'You can mark the path "react-is" as external to exclude it from the bundle, which will remove this error.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "react-is"'
    }
  ],
  warnings: []
}

Node.js v18.13.0
```
</details>

**Comment by swissspidy** [comment]
We are not yet using or compatible with React 18. So React 17 it is.

If you pass things like text elements to `OutputStory` etc. it expects the elements to be properly registered. So yes, you need `@googleforcreators/element-library` for that. `elementTypes.forEach(registerElementType);` is fine.

> However I can only create a string of AMP HTML, I can't quiet embed the AMP output into the page, as there's a warning/error saying that cannot next <html> tag inside a div, but I guess this is expected? and if so I am not sure what's the proper way to use <OutputStory/>

A valid web story is a full standalone HTML document incl. `<html>`, `<head>`, `<body>` etc. You can't put that inside a `<div>`

If you want to _embed_ a web story somewhere else, you'd need an iframe. The recommended way for doing so is to use the web story player, see https://amp.dev/documentation/guides-and-tutorials/stories/integrate/web-story-player-guide

**Comment by pietrop** [comment]
@swissspidy that's great thanks!

Where can I learn more about the specs for `OutputStory` props such as `story`,`pages` , `metadata` and `flags`? are they documented somewhere?

**Comment by swissspidy** [comment]
Yeah we haven't really properly documented that yet and have yet to convert it to TS. I guess looking at [the tests](https://github.com/GoogleForCreators/web-stories-wp/blob/2f21b00d44a954a63794988da0740ab33c6d1a7f/packages/output/src/test/story.js) would be a good start.

Basically:

* `story` - contains things like the story title, publisher logo, poster image
* `pages` - all the pages and their elements
* `metadata` - publisher name for the story
* `flags` - feature flags (currently unused)

**Comment by pietrop** [comment]
ok, cool, thanks! for the positioning of the [`elements`](https://github.com/GoogleForCreators/web-stories-wp/blob/2f21b00d44a954a63794988da0740ab33c6d1a7f/packages/elements/src/types/element.ts#L75-L90) (which I see extends an [element box](https://github.com/GoogleForCreators/web-stories-wp/blob/2f21b00d44a954a63794988da0740ab33c6d1a7f/packages/units/src/types.ts#L17-L23)) inside a [`page`](https://github.com/GoogleForCreators/web-stories-wp/blob/2f21b00d44a954a63794988da0740ab33c6d1a7f/packages/elements/src/types/page.ts) I see these are being implemented as [`amp-story-grid-layer`](https://amp.dev/documentation/examples/style-layout/amp_story_layouts/) ([api ref `amp-story-grid-layer`](https://amp.dev/documentation/components/amp-story-grid-layer)).

in `output` module json input for `pages`, is there a way to add `elements` without specifying a box position with coordinates (which seems a bit too rigid for our use case)? and leverage the css positioning offered by `amp-story-grid-layer`?

**Comment by swissspidy** [comment]
`amp-story-grid-layer` is neat for easily laying out elements vertically or horizontally or splitting the screen into three equally-sized rows.

The `output` package does not really use that though.  Instead, we use absolute positioning of all the elements with x/y coordinates within 1 single layer

**Comment by pietrop** [comment]
@swissspidy do you think there’s a straightforward way for me to modify the `output` module to support using the layout grid ? And if so where in the code might best to do that?

**Comment by swissspidy** [comment]
`element.js` is the place for modifying the output for each individual element on the page, and [`page.js`](https://github.com/GoogleForCreators/web-stories-wp/blob/2f21b00d44a954a63794988da0740ab33c6d1a7f/packages/output/src/page.js#L175-L191) for modifying the wrapping `amp-story-grid-layer`
