### ISSUE TITLE
Storybook not loading the editor 

### ISSUE THREAD

**Issue by santoshgistto** [swissspidy/web-stories-wp#13282]
Storybook not loading the edior 
## Logs
```
TypeError: Cannot read properties of undefined (reading 'RECTANGLE')

    at SaveButton (http://localhost:60332/main.iframe.bundle.js:231837:92)
    at div
    at O (http://localhost:60332/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_preview-698f24.iframe.bundle.js:155178:19697)
    at nav
    at O (http://localhost:60332/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_preview-698f24.iframe.bundle.js:155178:19697)
    at Buttons (http://localhost:60332/main.iframe.bundle.js:231674:92)
    at div
    at O (http://localhost:60332/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_preview-698f24.iframe.bundle.js:155178:19697)
    at header
    at O (http://localhost:60332/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_preview-698f24.iframe.bundle.js:155178:19697)
    at HeaderLayout
    at div
    at O (http://localhost:60332/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_preview-698f24.iframe.bundle.js:155178:19697)
    at section
    at O (http://localhost:60332/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_preview-698f24.iframe.bundle.js:155178:19697)
    at Layer (http://localhost:60332/main.iframe.bundle.js:128832:25)
    at http://localhost:60332/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_preview-698f24.iframe.bundle.js:157951:468
    at ChecklistCountProvider (http://localhost:60332/main.iframe.bundle.js:139812:27)
    at NavLayer (http://localhost:60332/main.iframe.bundle.js:130674:21)
    at div
    at O (http://localhost:60332/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_preview-698f24.iframe.bundle.js:155178:19697)
    at http://localhost:60332/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_preview-698f24.iframe.bundle.js:157951:468
    at WithOverlay (http://localhost:60332/main.iframe.bundle.js:70523:26)
    at SelectionCanvas (http://localhost:60332/main.iframe.bundle.js:132045:24)
    at div
    at O (http://localhost:60332/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_preview-698f24.iframe.bundle.js:155178:19697)
    at CanvasElementDropzone (http://localhost:60332/main.iframe.bundle.js:125520:23)
    at div
    at O (http://localhost:60332/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_preview-698f24.iframe.bundle.js:155178:19697)
    at http://localhost:60332/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_preview-698f24.iframe.bundle.js:157951:468
    at div
    at O (http://localhost:60332/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_preview-698f24.iframe.bundle.js:155178:19697)
    at UploadDropTarget (http://localhost:60332/main.iframe.bundle.js:212749:28)
    at CanvasUploadDropTarget (http://localhost:60332/main.iframe.bundle.js:125801:23)
    at section
    at O (http://localhost:60332/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_preview-698f24.iframe.bundle.js:155178:19697)
    at http://localhost:60332/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_preview-698f24.iframe.bundle.js:157951:468
    at EditLayerFocusManager (http://localhost:60332/main.iframe.bundle.js:127091:23)
    at ye (http://localhost:60332/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_preview-698f24.iframe.bundle.js:155178:12855)
    at CanvasLayout (http://localhost:60332/main.iframe.bundle.js:125680:22)
    at Canvas (http://localhost:60332/main.iframe.bundle.js:125444:21)
    at ErrorBoundary (http://localhost:60332/main.iframe.bundle.js:146976:5)
    at div
    at O (http://localhost:60332/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_preview-698f24.iframe.bundle.js:155178:19697)
    at http://localhost:60332/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_preview-698f24.iframe.bundle.js:157951:468
    at RichTextProvider (http://localhost:60332/main.iframe.bundle.js:76345:23)
    at http://localhost:60332/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_preview-698f24.iframe.bundle.js:157951:468
    at VideoTrimProvider (http://localhost:60332/main.iframe.bundle.js:213459:23)
    at Workspace (http://localhost:60332/main.iframe.bundle.js:214744:21)
    at http://localhost:60332/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_preview-698f24.iframe.bundle.js:157951:468
    at MediaRecordingProvider (http://localhost:60332/main.iframe.bundle.js:184024:23)
    at http://localhost:60332/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_preview-698f24.iframe.bundle.js:157951:468
    at RightClickMenuProvider (http://localhost:60332/main.iframe.bundle.js:117302:23)
    at http://localhost:60332/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_preview-698f24.iframe.bundle.js:157951:468
    at UnitsProvider (http://localhost:60332/main.iframe.bundle.js:222428:23)
    at http://localhost:60332/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_preview-698f24.iframe.bundle.js:157951:468
    at CanvasProvider (http://localhost:60332/main.iframe.bundle.js:96631:23)
    at section
    at O (http://localhost:60332/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_preview-698f24.iframe.bundle.js:155178:19697)
    at http://localhost:60332/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_preview-698f24.iframe.bundle.js:157951:468
    at WithOverlay (http://localhost:60332/main.iframe.bundle.js:70523:26)
    at http://localhost:60332/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_preview-698f24.iframe.bundle.js:157951:468
    at SidebarProvider (http://localhost:60332/main.iframe.bundle.js:206548:26)
    at http://localhost:60332/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_preview-698f24.iframe.bundle.js:157951:468
    at HighlightsProvider (http://localhost:60332/main.iframe.bundle.js:100206:23)
    at http://localhost:60332/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_preview-698f24.iframe.bundle.js:157951:468
    at ChecklistCheckpointProvider (http://localhost:60332/main.iframe.bundle.js:135572:23)
    at http://localhost:60332/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_preview-698f24.iframe.bundle.js:157951:468
    at LayoutProvider (http://localhost:60332/main.iframe.bundle.js:101316:23)
    at Layout (http://localhost:60332/main.iframe.bundle.js:167052:22)
    at http://localhost:60332/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_preview-698f24.iframe.bundle.js:157951:468
    at http://localhost:60332/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_preview-698f24.iframe.bundle.js:157951:468
    at PageDataUrlProvider (http://localhost:60332/main.iframe.bundle.js:112277:23)
    at http://localhost:60332/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_preview-698f24.iframe.bundle.js:157951:468
    at PageCanvasProvider (http://localhost:60332/main.iframe.bundle.js:111381:23)
    at http://localhost:60332/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_preview-698f24.iframe.bundle.js:157951:468
    at HelpCenterProvider (http://localhost:60332/main.iframe.bundle.js:99478:23)
    at http://localhost:60332/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_preview-698f24.iframe.bundle.js:157951:468
    at DropTargetsProvider (http://localhost:60332/main.iframe.bundle.js:146176:23)
    at http://localhost:60332/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_preview-698f24.iframe.bundle.js:157951:468
    at TransformProvider (http://localhost:60332/main.iframe.bundle.js:221488:23)
    at http://localhost:60332/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_preview-698f24.iframe.bundle.js:157951:468
    at MediaProvider (http://localhost:60332/main.iframe.bundle.js:105197:23)
    at http://localhost:60332/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_preview-698f24.iframe.bundle.js:157951:468
    at FontProvider (http://localhost:60332/main.iframe.bundle.js:98909:23)
    at http://localhost:60332/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_preview-698f24.iframe.bundle.js:157951:468
    at CurrentUserProvider (http://localhost:60332/main.iframe.bundle.js:98490:23)
    at http://localhost:60332/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_preview-698f24.iframe.bundle.js:157951:468
    at TaxonomyProvider (http://localhost:60332/main.iframe.bundle.js:124523:85)
    at http://localhost:60332/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_preview-698f24.iframe.bundle.js:157951:468
    at StoryTriggersProvider (http://localhost:60332/main.iframe.bundle.js:119387:24)
    at http://localhost:60332/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_preview-698f24.iframe.bundle.js:157951:468
    at StoryProvider (http://localhost:60332/main.iframe.bundle.js:118902:22)
    at http://localhost:60332/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_preview-698f24.iframe.bundle.js:157951:468
    at SnackbarProvider (http://localhost:60332/main.iframe.bundle.js:49150:23)
    at http://localhost:60332/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_preview-698f24.iframe.bundle.js:157951:468
    at HistoryProvider (http://localhost:60332/main.iframe.bundle.js:100675:23)
    at http://localhost:60332/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_preview-698f24.iframe.bundle.js:157951:468
    at Media3pApiProvider (http://localhost:60332/main.iframe.bundle.js:103712:23)
    at http://localhost:60332/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_preview-698f24.iframe.bundle.js:157951:468
    at APIProvider (http://localhost:60332/main.iframe.bundle.js:96412:24)
    at http://localhost:60332/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_preview-698f24.iframe.bundle.js:157951:468
    at ConfigProvider (http://localhost:60332/main.iframe.bundle.js:98221:21)
    at ErrorBoundary (http://localhost:60332/main.iframe.bundle.js:146976:5)
    at Fe (http://localhost:60332/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_preview-698f24.iframe.bundle.js:155178:17256)
    at ye (http://localhost:60332/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_preview-698f24.iframe.bundle.js:155178:12855)
    at FlagsProvider (http://localhost:60332/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_preview-698f24.iframe.bundle.js:70528:28)
    at StoryEditor (http://localhost:60332/main.iframe.bundle.js:215877:21)
    at div
    at http://localhost:60332/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_preview-698f24.iframe.bundle.js:157951:468
    at ConfigProvider (http://localhost:60332/main.iframe.bundle.js:98221:21)
    at Fe (http://localhost:60332/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_preview-698f24.iframe.bundle.js:155178:17256)
    at unboundStoryFn (http://localhost:60332/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_preview-698f24.iframe.bundle.js:18615:12)
    at ErrorBoundary (http://localhost:60332/vendors-node_modules_ap_cx_hues_dist_hues_umd_js-node_modules_storybook_addon-actions_preview-698f24.iframe.bundle.js:16131:5)
```

**Comment by swissspidy** [comment]
Fixed now!
