### ISSUE TITLE
Question: Trying to setup for standalone project

### ISSUE THREAD

**Issue by aletorrado** [swissspidy/web-stories-wp#13416]
Hi, I'm trying to implement story-editor for a non-react standalone project, so I followed the [tutorial](https://github.com/GoogleForCreators/web-stories-wp/blob/main/docs/third-party-integration/story-editor/tutorial.md), but I'm encountering some errors.

This is the code that I'm running. Please notice that I'm using no-jsx React just to easy my setup; that I had to comment out `elementTypes` and `registerElementType` because of TypeScript not being able to detect that export; and that I'm wrapping the editor into a html5 custom element.

```typescript
import {
	StoryEditor,
	InterfaceSkeleton,
} from "@googleforcreators/story-editor";
// import { elementTypes } from '@googleforcreators/element-library';
// import { registerElementType } from '@googleforcreators/elements';
import { createElement, render } from '@googleforcreators/react';
// import ReactDom from 'react-dom';
import { PolymerElement, html } from "@polymer/polymer";

// console.log(GReact)

const Editor = () => {
	const apiCallbacks = {
		saveStoryById: () => Promise.resolve({}),
	};

	// elementTypes.forEach(registerElementType);

	let skel = createElement(InterfaceSkeleton)
	let editor = createElement(StoryEditor, {
		config: apiCallbacks,
		initialEdits: { story: {} },
	}, skel)

	return editor

};

export default Editor;

export class FieldGstory extends PolymerElement {

	static get template(){
		return html`
			<div id="app"></div>
		`
	}

	connectedCallback(){
		super.connectedCallback()
		let editor = createElement(Editor)
		render(editor, this.$.app)
	}

}

customElements.define('field-gstory', FieldGstory)
```

This is just one of several errors that I'm getting:

```typescript
modal.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'colors')
    at i (modal.js:1:480)
    at Modal (modal.js:1:1025)
    at renderWithHooks (react-dom.development.js:14985:1)
    at mountIndeterminateComponent (react-dom.development.js:17811:1)
    at beginWork (react-dom.development.js:19049:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at beginWork$1 (react-dom.development.js:23964:1)
    at performUnitOfWork (react-dom.development.js:22779:1)
```

I was wondering if this project is still maintened for standalone setups, and if I could get some insights about what may be happening. Btw, I'm using React 17

**Comment by swissspidy** [comment]
Do you perhaps have a repository with your code so that we could try to replicate this?
